### ISSUE TITLE
Set up work plan

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Front-End-Ticketed-Project#6]
## SYSTEM / THEME
- [ ] write out all the font definitions and sizes in a type definition
- [ ] find all the colours in the style guide and write those up in a colours partial
- [ ] look at the spacing and find out if there any rules
- [ ] any other elements and system rules: images, icons, buttons, phrasing elements, form inputs

## COMPONENTS
- [ ] identify components
- [ ] estimate size/complexity of components 
- [ ] prioritise components (eg start with header)
